services:
  backend:
    build: ./
    container_name: capflow_backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - capflowDB
  capflowDB:
    image: postgres:16
    container_name: capflow_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: capflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - capflowDB

volumes:
  postgres_data:
